# Generated by Django 3.2 on 2021-05-16 22:29

from django.db import migrations, models
import hero.models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=hero.models.upload_path),
        ),
    ]
