# Generated by Django 3.2 on 2021-05-26 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_auto_20210526_0032'),
        ('hero', '0008_orderitem_user'),
    ]

    operations = [
    ]
