# Generated by Django 3.2 on 2021-07-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0010_item_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='test',
            field=models.CharField(default='test', max_length=5),
            preserve_default=False,
        ),
    ]
