# Generated by Django 3.2 on 2021-07-16 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0012_auto_20210716_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='test',
        ),
        migrations.AlterField(
            model_name='item',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='hero.todo'),
        ),
    ]
