# Generated by Django 3.2 on 2021-07-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0013_auto_20210716_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
