# Generated by Django 3.2 on 2021-04-29 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Book',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='itemname',
            new_name='title',
        ),
    ]
