version: "3.4"

services:
  core:
    image: core
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000

  core:
    image: frontend
    build:
      context: ./../Frontend
      dockerfile: ./../Frontend/Dockerfile
    ports:
      - 8000:8000
